name: API CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    env:
      working-directory: api

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Inspect PostgreSQL (on failure)
        run: |
          echo "${{ toJson(job) }}"
          docker logs "${{ job.services.postges.id }}"
        if: failure()
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.5
      - name: Cache Dependencies
        uses: actions/cache@v1
        with:
          path: ${{env.working-directory}}/vendor/bundle
          key: ${{ runner.os }}-bundler-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-bundler-
      - name: Setup
        env:
          DB_HOST: localhost
          RAILS_ENV: test
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          bundle exec rake db:create db:schema:load
        working-directory: ${{env.working-directory}}
      - name: Run Tests
        env:
          DB_HOST: 127.0.0.1
          RAILS_ENV: test
        run: |
          bundle exec rspec
        working-directory: ${{env.working-directory}}
      # https://github.com/codecov/codecov-bash
      - name: Upload Coverage Report
        run: |
          bash <(curl -s https://codecov.io/bash) -Z
  lint:
    name: Run Linter
    runs-on: ubuntu-latest
    env:
      working-directory: api

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.5
      - name: Cache Dependencies
        uses: actions/cache@v1
        with:
          path: ${{env.working-directory}}/vendor/bundle
          key: ${{ runner.os }}-bundler-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-bundler-
      - name: Setup
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
        working-directory: ${{env.working-directory}}
      - name: Lint
        run: |
          bundle exec rubocop
        working-directory: ${{env.working-directory}}
